"""
PustakaDesk — utils/export.py
Fungsi ekspor data ke CSV dan PDF.
"""

import csv

from reportlab.platypus import (
    SimpleDocTemplate,
    Table,
    TableStyle,
    Paragraph,
    Spacer
)

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import getSampleStyleSheet


def export_csv(rows, filepath, headers) -> str:
    """
    Export data ke CSV.
    Encoding utf-8-sig agar aman dibuka di Excel.
    """

    with open(filepath, "w", newline="", encoding="utf-8-sig") as file:

        writer = csv.writer(file)

        writer.writerow(headers)

        for row in rows:
            writer.writerow(row)

    return filepath


def export_pdf(rows, filepath, judul_laporan, headers, subtitle="") -> str:
    """
    Export data ke PDF menggunakan reportlab.
    """

    doc = SimpleDocTemplate(
        filepath,
        pagesize=landscape(A4),
        rightMargin=24,
        leftMargin=24,
        topMargin=24,
        bottomMargin=24
    )

    elements = []

    styles = getSampleStyleSheet()

    title = Paragraph(
        f"<b>{judul_laporan}</b>",
        styles["Title"]
    )

    elements.append(title)
 
    if subtitle:
        sub = Paragraph(subtitle, styles["Normal"])
        elements.append(sub)

    elements.append(Spacer(1, 12))

    table_data = [headers]

    for row in rows:
        table_data.append(list(row))

    table = Table(table_data, repeatRows=1)

    style = TableStyle([

        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1E2D3D")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 10),

        ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 1), (-1, -1), 9),

        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),

        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),

        ("BOTTOMPADDING", (0, 0), (-1, 0), 10),
        ("TOPPADDING", (0, 0), (-1, 0), 10),
    ])

    for i in range(1, len(table_data)):

        if i % 2 == 0:
            bg = colors.whitesmoke
        else:
            bg = colors.beige

        style.add(
            "BACKGROUND",
            (0, i),
            (-1, i),
            bg
        )

    table.setStyle(style)

    elements.append(table)

    elements.append(Spacer(1, 14))

    footer = Paragraph(
        f"""
        <font size=9>
        Total Data: <b>{len(rows)}</b><br/>
        Generated by <b>PustakaDesk</b>
        </font>
        """,
        styles["Normal"]
    )

    elements.append(footer)

    doc.build(elements)

    return filepath